#!/bin/bash

GF_SCRIPTS_DIR="/pi_dev_scripts/builtin"
GF_SKETCH_FILE="/home/pi_dev/workdir/GF_SKETCH.md"
GF_TODO_FILE="/home/pi_dev/workdir/GF_TODO.md"

cd /home/pi_dev/workdir

run_bash() {
	bash
}

run_pi() {
	pi
}

run_pi_select() {
	pi -r
}

run_pi_continue() {
	pi -c
}

automation_menu() {
	while true; do
		clear
		echo ""
		echo "You're in a pi.dev box automation menu!"
		echo ""
		echo "Select action:"
		echo ""
		echo "[S] Prepare/update SKETCH - file where you define what would you like to have coded"
		if [ -f $GF_SKETCH_FILE ]; then
			echo "[P] Convert SKETCH to TODO file"
			echo "[Q] Convert SKETCH to TODO file with interactive shell"
		fi
		echo "[T] Prepare/update TODO   - file where you define exact steps for automatic coder"
		if [ -f $GF_TODO_FILE ]; then
			echo "[R] Run automatic development based on TODO file"
			echo "[C] Run automatic development based on TODO file with internal critic"
		fi
		echo ""
		echo "[X] back to main menu"
		echo ""
		read -p "Selected action: " actionToRun
		case "$actionToRun" in
		x | X)
			break
			;;
		s | S)
			clear
			vim $GF_SKETCH_FILE
			;;
		p | P)
			clear
			run_pi_noninteractive_with_script "auto_planner"
			;;
		q | Q)
			clear
			run_pi_interactive_with_script "auto_planner"
			;;
		t | T)
			clear
			vim $GF_TODO_FILE
			;;
		r | R)
			clear
			local roundNumber=1
			while [[ -f "$GF_TODO_FILE" ]]; do
				echo "Running iteration #$roundNumber"
				run_pi_noninteractive_with_script "auto_programmer"
				roundNumber=$((roundNumber + 1))
			done
			;;
		c | C)
			clear
			local roundNumber=1
			while [[ -f "$GF_TODO_FILE" ]]; do
				echo "Running iteration #$roundNumber"
				run_pi_noninteractive_with_script "auto_programmer"
				if [ -f $GF_TODO_FILE ]; then
					run_pi_noninteractive_with_script "auto_critic"
				fi
				roundNumber=$((roundNumber + 1))
			done
			;;
		*)
			echo ""
			;;
		esac
	done
}

run_pi_noninteractive_with_script() {
	local scriptName=$1
	local fullScriptPath="$GF_SCRIPTS_DIR/$scriptName.txt"
	if [ -f "$fullScriptPath" ]; then
		local scriptContent=$(cat "$fullScriptPath")
		echo "Running script $scriptName..."
		pi -p "$scriptContent"
	else
		echo "ERROR: $fullScriptPath NOT FOUND"
		sleep 5
	fi
}

run_pi_interactive_with_script() {
	local scriptName=$1
	local fullScriptPath="$GF_SCRIPTS_DIR/$scriptName.txt"
	if [ -f "$fullScriptPath" ]; then
		local scriptContent=$(cat "$fullScriptPath")
		echo "Starting script..."
		pi "$scriptContent"
	else
		echo "ERROR: $fullScriptPath NOT FOUND"
		sleep 5
	fi
}

kickoff_menu() {
	while true; do
		clear
		echo ""
		echo "You're in a pi.dev box kick-off menu!"
		echo ""
		echo "Select action:"
		echo ""
		echo "[C] Start Code Review"
		echo "[I] Propose Improvements"
		echo "[R] Update Readme"
		echo ""
		echo "[X] back to main menu"
		echo ""
		read -p "Selected action: " actionToRun
		case "$actionToRun" in
		x | X)
			break
			;;
		c | C)
			clear
			run_pi_interactive_with_script "init_code_review"
			;;
		i | I)
			clear
			run_pi_interactive_with_script "init_improvements"
			;;
		r | R)
			clear
			run_pi_interactive_with_script "init_readme"
			;;
		*)
			echo ""
			;;
		esac
	done
}

run_main() {
	local actionToRun
	while true; do
		clear
		echo ""
		echo "You're in a pi.dev box!"
		echo ""
		echo "Select action:"
		echo "[N] New session"
		echo "[C] Continue last session"
		echo "[S] Select session"
		echo ""
		echo "[A] Automation"
		echo "[K] New session with builtin conversation-starter"
		echo "[B] Bash"
		echo ""
		echo "[X] exit / detach from container"
		echo ""
		read -p "Selected action: " actionToRun
		case "$actionToRun" in
		x | X)
			echo "👋 Bye!"
			exit 0
			break
			;;
		b | B)
			clear
			run_bash
			;;
		n | N)
			clear
			run_pi
			;;
		s | S)
			clear
			run_pi_select
			;;
		c | C)
			clear
			run_pi_continue
			;;
		a | A)
			clear
			automation_menu
			;;
		k | k)
			clear
			kickoff_menu
			;;
		*)
			echo ""
			;;
		esac
	done
}

run_main
