#!/bin/bash
#####
GF_INFERENCE_COMPOSE_FILE_SOURCE='../data/shared/inference_config.yml'
GF_INFERENCE_COMPOSE_FILE_TARGET='../docker/llama_cpp/compose.override.yml'
GF_INFERENCE_PRESET_NAME_DESIRED='../data/shared/inference_preset_name_target.txt'
GF_INFERENCE_PRESET_NAME='../data/shared/inference_preset_name.txt'
GF_INFERENCE_PRESETS_DIR_EXAMPLE='../data/shared/inference_presets/examples/'
GF_INFERENCE_PRESETS_DIR_LOCAL='../data/shared/inference_presets/local/'
GF_INFERENCE_PRESETS_LOADING_TIMES='../data/shared/inference_loading_times.txt'
GF_INFERENCE_SERVICE_UP_STATUS='../data/shared/inference_status.txt'
GF_INFERENCE_URL="http://localhost:8080"
GF_LOAD_TIMEOUT=300
#####

skipLoadingTimeCheck=0

add_minimal_padding() {
	local var="$1"
	local min_len="${2:-2}"
	local align="${3:-right}" # 'left' or 'right' (default)

	while [[ ${#var} -lt min_len ]]; do
		if [[ "$align" == "right" ]]; then
			var+=" " # Append space
		else
			var=" $var" # Prepend space
		fi
	done
	echo "$var"
}

fail_preflight_on_missing_binary() {
	if [ "$(has_binary $1)" -ne "1" ]; then
		echo "Preflight check failed, missing binary from the system: $1"
		exit 127
	fi
}

get_preset_loading_time() {
	local preset_name="$1"
	if [ -f "$GF_INFERENCE_PRESETS_LOADING_TIMES" ]; then
		local time_val
		time_val=$(awk -v p="$preset_name" '$1 == p {print $2; exit}' "$GF_INFERENCE_PRESETS_LOADING_TIMES")
		if [ -n "$time_val" ]; then
			echo "$time_val"
			return
		fi
	fi
	echo "999"
}

has_binary() {
	if [ -f "$(which $1)" ]; then
		echo "1"
	else
		echo "0"
	fi
}

is_preset_name_currently_running() {
	local currentPresetName=""
	if [ -f "$GF_INFERENCE_PRESET_NAME" ]; then
		currentPresetName=$(cat "$GF_INFERENCE_PRESET_NAME")
	fi
	if [[ "$currentPresetName" == $1 ]]; then
		local inferenceServerStatus=$(cat "$GF_INFERENCE_SERVICE_UP_STATUS")
		if [[ "$inferenceServerStatus" == 'RUNNING' ]]; then
			echo "1"
			return 0
		fi
	fi
	echo "0"
}

load_preset_file() {
	if [ -f "$1" ]; then
		local checkSum=$(md5sum "$GF_INFERENCE_COMPOSE_FILE_SOURCE" | xargs | cut -d " " -f 1)
		local desiredCheckSum=$(md5sum "$1" | xargs | cut -d " " -f 1)
		if [[ $desiredCheckSum == "$checkSum" ]]; then
			echo "Preset already loaded!"
			exit 0
		fi

		cat "$1" >"$GF_INFERENCE_COMPOSE_FILE_SOURCE"
		basename $1 | cut -d "." -f 1 >"$GF_INFERENCE_PRESET_NAME_DESIRED"
		checkSum=$desiredCheckSum

		if [ "$skipLoadingTimeCheck" -eq 1 ]; then
			exit 0
		fi

		local currentStatus=$(cat $GF_INFERENCE_SERVICE_UP_STATUS)
		if [[ $currentStatus == 'LOCKED' ]]; then
			exit 0
		fi

		local loadingStart=$(date +%s)
		echo "Waiting for daemon to load preset..."
		local presetToLoad=$(cat "$GF_INFERENCE_PRESET_NAME_DESIRED")
		local loadingTimeEstimate=$(get_preset_loading_time $checkSum)
		local isReady=$(is_preset_name_currently_running $presetToLoad)
		while [[ $isReady == '0' ]]; do
			actualLoadingTime=$(($(date +%s) - $loadingStart))
			if [ $actualLoadingTime -gt $GF_LOAD_TIMEOUT ]; then
				# Probably loaded in blink of an eye
				exit 0
			fi
			echo -ne "[ $(add_minimal_padding $actualLoadingTime 3 left) / $loadingTimeEstimate ]\r"
			sleep 1
			isReady=$(is_preset_name_currently_running $presetToLoad)
		done
		echo "Preset loaded!"

		if grep -q "^${checkSum} " "$GF_INFERENCE_PRESETS_LOADING_TIMES" 2>/dev/null; then
			sed -i "s/^${checkSum} .*/${checkSum} ${actualLoadingTime}/" "$GF_INFERENCE_PRESETS_LOADING_TIMES"
		else
			echo "${checkSum} ${actualLoadingTime}" >>"$GF_INFERENCE_PRESETS_LOADING_TIMES"
		fi
	fi
	exit 0
}

load_preset() {
	local presetIdentifier=$1

	local presetFiles=$(find $GF_INFERENCE_PRESETS_DIR_LOCAL | grep '.yml')
	if [ -z "$presetFiles" ]; then
		presetFiles=$(find $GF_INFERENCE_PRESETS_DIR_EXAMPLE | grep '.yml')
	fi
	for presetFile in $presetFiles; do
		local fullPath=$presetFile
		local presetName=$(basename $presetFile)
		if [[ "$presetIdentifier" == "$presetName" ]]; then
			load_preset_file $fullPath
		fi

		local presetNameShort=$(echo $presetName | cut -d "." -f 1)
		if [[ "$presetIdentifier" == "$presetNameShort" ]]; then
			load_preset_file $fullPath
		fi

		local checkSum=$(md5sum "$fullPath" | xargs | cut -d " " -f 1)
		if [[ "$presetIdentifier" == "$checkSum" ]]; then
			load_preset_file $fullPath
		fi
	done
	echo "Preset not found: $presetIdentifier"
	exit 1
}

run_main() {
	run_preflight_checks
	if [ -z "$1" ]; then
		show_available_presets
	else
		load_preset $1
	fi
}

run_preflight_checks() {
	fail_preflight_on_missing_binary awk
	fail_preflight_on_missing_binary basename
	fail_preflight_on_missing_binary cat
	fail_preflight_on_missing_binary find
	fail_preflight_on_missing_binary grep
	fail_preflight_on_missing_binary sed
}

show_available_presets() {
	echo "Use one of below names as script's first argument to load preset:"
	local presetFiles=$(find $GF_INFERENCE_PRESETS_DIR_LOCAL | grep '.yml')
	if [ -z "$presetFiles" ]; then
		echo "Listing example presets (no local presets found)"
		presetFiles=$(find $GF_INFERENCE_PRESETS_DIR_EXAMPLE | grep '.yml')
	fi

	local currentPresetHash="XYZ!@#"
	if [ -f "$GF_INFERENCE_COMPOSE_FILE_TARGET" ]; then
		currentPresetHash=$(md5sum "$GF_INFERENCE_COMPOSE_FILE_TARGET" | xargs | cut -d " " -f 1)
	fi

	for presetFile in $presetFiles; do
		local fullPath=$presetFile
		local presetName=$(basename $presetFile)
		local checkSum=$(md5sum "$fullPath" | xargs | cut -d " " -f 1)
		local loadingTime=$(get_preset_loading_time $checkSum)

		local ctxSize=$(grep "ctx-size" "$presetFile" | xargs | cut -d " " -f 2)
		if [ -z "$ctxSize" ]; then
			ctxSize="???"
		fi

		presetName=$(echo "$presetName" | cut -d '.' -f 1)
		presetName=$(add_minimal_padding " - $presetName" 39)
		loadingTime=$(add_minimal_padding "$loadingTime" 3 "left")
		ctxSize=$(add_minimal_padding "$ctxSize" 6 "left")

		local isActiveSuffix=""
		if [[ "$checkSum" == "$currentPresetHash" ]]; then
			isActiveSuffix=" [ ACTIVE ]"
		fi
		echo "$presetName [ ~ ${loadingTime} s ] [ CTX: $ctxSize ]$isActiveSuffix"

	done
}

if [ -z "$2" ]; then
	skipLoadingTimeCheck=0
else
	skipLoadingTimeCheck=1
fi

clear
run_main $1
